In [2]:
import numpy as np
#Creare un array es2a di valori casuali interi (randint) di dimensione 4x6, con valore massimo (incluso) uguale a 15.
es2a= np.random.randint(16, size=(4,6))
es2a

array([[ 1,  0,  8,  3, 14,  7],
       [ 3,  8,  0,  2, 13,  9],
       [ 5, 12,  9, 15, 15, 12],
       [ 5,  4, 10, 11, 13,  5]])

In [3]:
#1. prime tre righe, prime tre colonne
es2a[:3,:3]

array([[ 1,  0,  8],
       [ 3,  8,  0],
       [ 5, 12,  9]])

In [4]:
#2. seconda e terza riga, quarta, quinta e sesta colonna
es2a[1:3, 3:6]

array([[ 2, 13,  9],
       [15, 15, 12]])

In [5]:
#3. elementi dopo il terzo elemento
es2a[2:]

array([[ 5, 12,  9, 15, 15, 12],
       [ 5,  4, 10, 11, 13,  5]])

In [6]:
#4. invertire l’ordine delle sole righe; invertire l’ordine delle sole colonne
print("array non invertito:\n", es2a, "\n")
print("inverto righe:\n", es2a[::-1,:], "\n")
print("inverto colonne:\n", es2a[:,::-1], "\n")

array non invertito:
 [[ 1  0  8  3 14  7]
 [ 3  8  0  2 13  9]
 [ 5 12  9 15 15 12]
 [ 5  4 10 11 13  5]] 

inverto righe:
 [[ 5  4 10 11 13  5]
 [ 5 12  9 15 15 12]
 [ 3  8  0  2 13  9]
 [ 1  0  8  3 14  7]] 

inverto colonne:
 [[ 7 14  3  8  0  1]
 [ 9 13  2  0  8  3]
 [12 15 15  9 12  5]
 [ 5 13 11 10  4  5]] 



In [7]:
#Creare un array es2b di valori casuali interi (randint) di dimensione 5x5x2, con valore massimo (incluso) uguale a 30.
es2b= np.random.randint(31, size=(5,5,2))
es2b

array([[[26, 16],
        [30,  4],
        [20,  4],
        [22, 19],
        [21, 26]],

       [[ 0, 23],
        [11, 24],
        [29,  9],
        [13, 22],
        [10,  5]],

       [[ 2, 30],
        [ 4, 10],
        [ 4, 10],
        [ 4, 16],
        [16, 12]],

       [[ 1, 13],
        [23, 25],
        [24, 24],
        [14,  9],
        [21,  5]],

       [[ 7,  2],
        [ 8, 23],
        [ 1, 18],
        [23, 19],
        [29, 21]]])

In [8]:
#1. selezionare il primo subarray, da quello le prime 2 righe e le colonne dalla seconda alla quarta
es2b[:1,:2,1:4]

array([[[16],
        [ 4]]])

In [9]:
#2. selezionare da entrambi i subarray le prime due righe e prime due colonne e invertire righe e colonne
a= es2b[:2, :2,:2]
print("array non invertito:\n", a, "\n")
print("inverto righe:\n", a[:,::-1,:], "\n")
print("inverto colonne:\n", a[:,:,::-1], "\n")
print("inverto righe e colonne:\n", a[:,::-1,::-1], "\n")

array non invertito:
 [[[26 16]
  [30  4]]

 [[ 0 23]
  [11 24]]] 

inverto righe:
 [[[30  4]
  [26 16]]

 [[11 24]
  [ 0 23]]] 

inverto colonne:
 [[[16 26]
  [ 4 30]]

 [[23  0]
  [24 11]]] 

inverto righe e colonne:
 [[[ 4 30]
  [16 26]]

 [[24 11]
  [23  0]]] 

