In [5]:
#creo array di 10 valori che parte da 5 e va a 15
import numpy as np
es1= np.arange(5,15)
es1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
#estraggo primi 6 valori
es1[:6]

array([ 5,  6,  7,  8,  9, 10])

In [7]:
#elementi dopo il terzo valore
es1[3:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [8]:
#elementi dopo l'indice 3
print("elemento di indice 3:", es1[3])
print("elementi dopo quello di indice 3:", es1[4:])

elemento di indice 3: 8
elementi dopo quello di indice 3: [ 9 10 11 12 13 14]


In [9]:
#subarray con valori 8,9,10,11,12
es1[3:8]

array([ 8,  9, 10, 11, 12])

In [10]:
#un elemento ogni tre partendo dal primo
es1[::3]

array([ 5,  8, 11, 14])

In [12]:
#un elemento ogni tre partendo dal terzo
es1[2::3]

array([ 7, 10, 13])