In [40]:
import numpy as np
x = np.array([1, 2, 3, 4])
print(x)
x.reshape((2, 2))


[1 2 3 4]


array([[1, 2],
       [3, 4]])

In [6]:
x[np.newaxis, :2]

array([[1, 2]])

In [7]:
x[np.newaxis, 2:]

array([[3, 4]])

In [42]:
#1. Creare una lista es4 di 36 valori interi crescenti partendo da 1
es4= np.arange(1,37)
print("es4:\n", es4, "\n")

es4:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36] 



In [46]:
#2. Trasformarlo in un array di dimensione 6x6
es4= es4.reshape(6,6)
print("es4:\n", es4, "\n")

es4:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]] 



In [16]:
#3. Estrarre tre subarray di dimensione 2x2 dalle prime due colonne (sub1, sub2, sub3)
sub1= es4[:2,:2]
sub2= es4[2:4,:2]
sub3= es4[4:6,:2]
print("sub1:\n", sub1, "\n")
print("sub2:\n", sub2, "\n")
print("sub3:\n", sub3, "\n")

sub1:
 [[1 2]
 [7 8]] 

sub2:
 [[13 14]
 [19 20]] 

sub3:
 [[25 26]
 [31 32]] 



In [17]:
#4. Concatenarli (usare concatenate) prima usando axis=0 poi con axis=1
np.concatenate([sub1, sub2, sub3], axis=0)


array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20],
       [25, 26],
       [31, 32]])

In [47]:
#5. Da es4 estrarre un subarray formato dalle prime due righe (sub4)
sub4= es4[:2,:]
print("sub4:\n", sub4, "\n")

sub4:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 



In [48]:
#6. Concatenare sub1 a sub4. Usate hstack o vstack?
print("sub1:\n", sub1, "\n")
print("sub4:\n", sub4, "\n")
np.hstack([sub1,sub4])

sub1:
 [[1 2]
 [7 8]] 

sub4:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 



array([[ 1,  2,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  7,  8,  9, 10, 11, 12]])

In [37]:
#7. Trasformate sub4 da 2x6 a 6x2 (le 2 righe diventano 2 colonne)
sub4= sub4.reshape(6,2)
print("sub4:\n", sub4, "\n")

sub4:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]] 



In [49]:
#8. Concatenate sub1, sub2 e sub3 a formare un nuovo array 6x2 (sub5)
sub5= np.concatenate([sub1, sub2, sub3])
print("sub5:\n", sub5, "\n")

sub5:
 [[ 1  2]
 [ 7  8]
 [13 14]
 [19 20]
 [25 26]
 [31 32]] 



In [50]:
#9. Concatenate sub4 (trasformato) con sub5. hstack o vstack?
print("sub4:\n", sub4, "\n")
print("sub5:\n", sub5, "\n")
a= np.hstack([sub4,sub5])
print("a:\n", a, "\n")
b= np.vstack([sub4, sub5])
print("b:\n", b, "\n")

sub4:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 

sub5:
 [[ 1  2]
 [ 7  8]
 [13 14]
 [19 20]
 [25 26]
 [31 32]] 



ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 6