In [1]:
import numpy as np
#Creare un array es3 di valori casuali interi (randint) di dimensione 3x3, con valore massimo (incluso) uguale a 20
es3= np.random.randint(21, size=(3,3))
es3

array([[19,  2,  7],
       [ 3, 16,  1],
       [ 1, 19, 12]])

In [4]:
#2. estrarre il subarray formato dalla seconda riga (es3-sub) come vista e visualizzarlo
es3_sub= es3[:2,:]
es3_sub

array([[19,  2,  7],
       [ 3, 16,  1]])

In [13]:
#3. moltiplicare per 3 tutti gli elementi della seconda colonna di es3
print("valori prima della moltiplicazione:\n", es3[:,:2])
print("valori dopo la moltiplicazione:\n", es3[:,:2]*3)

valori prima della moltiplicazione:
 [[19  2]
 [ 3 16]
 [ 1 19]]
valori dopo la moltiplicazione:
 [[57  6]
 [ 9 48]
 [ 3 57]]


In [14]:
#4. visualizzare es3-sub. È cambiato rispetto a prima?
es3_sub

array([[19,  2,  7],
       [ 3, 16,  1]])

In [15]:
#5. estrarre il subarray formato dalla terza colonna di es3 come copia (es3-sub-copy)
es3_sub_copy= es3[:,2]
es3_sub_copy

array([ 7,  1, 12])

In [17]:
#6. sommare 10 a tutti gli elementi di es3-sub-copy e visualizzare
print("es3_sub_copy:\n", es3_sub_copy, "\n")
print("es3_sub_copy + 10:\n", es3_sub_copy+10, "\n")


es3_sub_copy:
 [ 7  1 12] 

es3_sub_copy + 10:
 [17 11 22] 

